### PR TITLE
Corp dev

### PR DESCRIPTION
**Pull request by corpandrew**
Map Updates (Directions with a polyline, check in with a circle, and radius location search circle).
Removed the marker icon as the check-in circle does the job.
Check In button only becomes available when you are within the radius of the location.
Fixed Buttons to show properly on Android.
Adding lazy scoring - will update the scoring soon.

### CODE REVIEW

**Comment by tenhagena** [comment]
I like it,  I added CHECKINDIST, but everything else looks good

**Review by tenhagena — APPROVED** [review]
LGTM

**Review by tenhagena — CHANGES_REQUESTED** [review]
DO NOT MERGE THIS PLZ

**Review by tenhagena — APPROVED** [review]
Everything should work....

**Comment by cmonteiro128** [comment]
Includes modal functionality

**Pull request merged**
